### ISSUE TITLE
Need to fix StoryText field - 

### ISSUE THREAD

**Issue by hs127** [1Fungi99/Shelve-It#15]
It is capturing as following {"ops":[{"insert":"Composing Masterpiece to test the draft function and to see if it will post. Test TEst. test. need eight more characters. \n"}]}

Need to get rid of {"ops}:[{"insert.... \n"}]}

- [x] Implement Quill Editor in readme only mode to display data the same way it was entered by author's.

**Comment by EmirVelazquez** [comment]
Completed. Resolved this bug, had to implement quill editor to display the json data properly.
